name: todo_list_app
description: TodoList app for storing and doning tasks
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dio: ^5.2.1
  envied: ^0.3.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  intl: any
  json_annotation: ^4.8.1
  logging: ^1.2.0
  mockito: ^5.4.2
  path_provider: ^2.0.15
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.1.2
  sqflite: ^2.2.8
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.5
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

flutter_intl:
  enabled: true
