// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiooRGX-xPj_5FKCup3YylmHG7bSeOyw0',
    appId: '1:87832376050:web:19d047954809323137166b',
    messagingSenderId: '87832376050',
    projectId: 'firebase-todo-list-app',
    authDomain: 'fir-todo-list-app-58f59.firebaseapp.com',
    storageBucket: 'firebase-todo-list-app.appspot.com',
    measurementId: 'G-SFCCME5M9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAUX_VDmR2_eAyaAcOJhqXQ3St5j3i3vM',
    appId: '1:87832376050:android:985f62300e967f2d37166b',
    messagingSenderId: '87832376050',
    projectId: 'firebase-todo-list-app',
    storageBucket: 'firebase-todo-list-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjNMVzvNwBAtUjGrSJ34ztFVISMbUxJ6Q',
    appId: '1:87832376050:ios:d4a263d9717a4ede37166b',
    messagingSenderId: '87832376050',
    projectId: 'firebase-todo-list-app',
    storageBucket: 'firebase-todo-list-app.appspot.com',
    iosClientId: '87832376050-iq1hvqq95ck517qvpgbb8j4bqos63fgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjNMVzvNwBAtUjGrSJ34ztFVISMbUxJ6Q',
    appId: '1:87832376050:ios:2330881ef3b6f5b737166b',
    messagingSenderId: '87832376050',
    projectId: 'firebase-todo-list-app',
    storageBucket: 'firebase-todo-list-app.appspot.com',
    iosClientId: '87832376050-tbovm51teevf74ubbfs21cetmohj4tft.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp.RunnerTests',
  );
}
